import React from 'react'
import "./web_dev.css";
const Webs = () => {
    return (
        <>
            <div className="aboutbox1">
                    <h1><span>Static Website</span></h1>
                    <img src="https://webdwizcom.files.wordpress.com/2021/07/static-website.jpg" alt=""/>
                    <p>A static web page is a web page that is delivered to the user’s web browser exactly as stored, in contrast to dynamic web pages which are generated by a web application.</p>
                </div>
            <div className="aboutbox1">
                    <h1><span>E-commerce Website</span></h1>
                    <img src="https://webdwizcom.files.wordpress.com/2021/07/e-commerce-solution-500x500-1.png" alt=""/>
                    <p>Senior Product Designer at Vaxx and is responsible for transforming UX across the company’s products. Previously, he held leadership roles at T An e-commerce website, by definition, is a website that allows you to buy and sell tangible goods, digital products or services online. Trade, be it barter exchange or buying and selling of goods and services has been prevalent for centuries. No one can be self-sufficient. And this brings out the need for demand and supply of goods and services. </p>
                </div>
            
        </>
    )
}
export  default Webs;
